# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_time', models.DateTimeField()),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WildAnimalsRegister.Animal')),
            ],
        ),
    ]
