# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WildAnimalsRegister', '0003_auto_20170325_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='last_seen_time',
            field=models.DateTimeField(default='25.03.2017'),
        ),
    ]
