# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='difficulty_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='tunnitöö', max_length=255),
            preserve_default=False,
        ),
    ]
