# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170216_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_name',
            new_name='name',
        ),
    ]
