# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170216_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.Boolean'),
        ),
    ]
