# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WildAnimalsRegister', '0005_auto_20170325_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
